[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
ed25519-dalek = { version = "2.1.1", features = ["pem", "rand_core"] }
reqwest = { version = "0.12.12", features = ["json"] }
serde = { version = "1.0.217", features = ["derive"] }
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
