[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.1", features = ["tracing"] }
base64 = "0.22.1"
ed25519 = "2.2.3"
ed25519-dalek = { version = "2.1.1", features = ["pem", "rand_core"] }
rand = "0.8.5"
serde = { version = "1.0.217", features = ["derive"] }
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
